# LinkForge Backend — Render Blueprint (IaC)

services:
  - type: web
    name: linkforge-backend
    runtime: docker
    repo: https://github.com/tlavu2004/linkforge-backend
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      # Spring Profile
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      # Connect to the Environment Group you created
      - fromGroup: linkforge-secrets

      # Default values (can be overridden by Env Group if needed)
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_SSL_ENABLED
        value: "true"
      - key: PORT
        value: "10000"
      - key: FRONTEND_URL
        value: "https://tlavu-linkforge.vercel.app"
      - key: BACKEND_URL
        value: "https://linkforge-backend-r0tk.onrender.com"
      - key: VNPAY_URL
        value: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
      - key: VNPAY_RETURN_URL
        value: "https://linkforge-backend-r0tk.onrender.com/api/v1/payments/vnpay-return"
      - key: VNPAY_API_URL
        value: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
      - key: MAIL_HOST
        value: "smtp-relay.brevo.com"
      - key: MAIL_PORT
        value: "2525"

      # JWT (Render can auto-generate this if not in Env Group)
      - key: JWT_EXPIRATION
        value: "900000"
      - key: JWT_REFRESH_TOKEN_EXPIRATION
        value: "604800000"
      - key: JWT_SECRET_KEY
        generateValue: true
